version: '2.2'
services:
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-1
    restart: always
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-application:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: spark-application
    ports:
    - "4040:4040"
    depends_on:
      - spark-master
    environment:
      - ENABLE_INIT_DAEMON="false"
    restart: always